### ISSUE TITLE
[baduser] make the report an embed that's prettier than the code block

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/misc-cogs#297]
[timestamp](link to message): text of message
[timestamp](link to message): text of message
[timestamp](link to message): text of message
[timestamp](link to message): text of message

and we don't need to show the name uuid next to each message cos it's just one user per screen so display those things in the title of the embed

**Comment by ethannp** [comment]
comment

**Comment by RheingoldRiver** [comment]
This has no interactivity of any sort because it wasn't created by any command, so no need for menu2
