### ISSUE TITLE
[remindme] Add option to set time zone private

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/misc-cogs#42]
If you toggle this on, then Tsubaki should not say the name of your time zone when she confirms a remindme and instead say "your time zone"

`^remindme toggletzprivate`

"Ok, your time zone is now set to PRIVATE. I will HIDE your time zone when I confirm your reminders."

"Ok, your time zone is now set to PUBLIC. I will SHOW your time zone when I confirm your reminders."

the code you will edit is in `timecog`

**Comment by turtleworks** [comment]
note that tsubaki conventions have changed to using **bold** instead of ALL CAPS for indicating notable changes
